### ISSUE TITLE
[bug] Unreferenced citation rendered on document with other citations

### ISSUE THREAD

**Issue by najuzilu** [ExecutableBookProject/myst-parser.example-project#11]
There's an issue with citations which was first introduced by @mtiley here ExecutableBookProject/MyST-Parser#95. I think the issue is that we have multiple documents referencing the same `references.bib` file. 

@mmcky @mtiley, could let me know if you get the same issue when rendering `finite_markov-MyST` locally (see image below citation 4)? If yes, I'll look more into this problem.

<img width="880" alt="citation_issue" src="https://user-images.githubusercontent.com/33075058/76133021-21e9ed00-606a-11ea-9946-0c6538d418f5.png">

**Comment by chrisjsewell** [comment]
Yeh that’s what I suspect. Obviously let me know when/if I can close the issue on MyST-Parser
