### ISSUE TITLE
PDF Support

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/myst-parser.example-project#16]
The `latex` generated from `rst` sources around line 93

```latex
\chapter{Dynamics in One Dimension}
\label{\detokenize{scalar_dynam:dynamics-in-one-dimension}}\label{\detokenize{scalar_dynam::doc}}\index{Dynamics in One Dimension@\spxentry{Dynamics in One Dimension}}
\begin{sphinxShadowBox}
\sphinxstyletopictitle{Contents}
\begin{itemize}
```

compare to the latex generated from the `myst` sources around line 93

```latex
\chapter{\label{\detokenize{scalar_dynam-MyST:scalar-d}} Dynamics in One Dimension}
\label{\detokenize{scalar_dynam-MyST:dynamics-in-one-dimension}}\label{\detokenize{scalar_dynam-MyST::doc}}
\begin{sphinxShadowBox}
\sphinxstyletopictitle{Contents}
\begin{itemize}
```

It is interested as the myst output has included labels within the chapter name likely causing an issue.

**Comment by mmcky** [comment]
@chrisjsewell have we compared the `AST` produced from `rst` and `myst` source files that contains the same content (not markup clearly)? Just trying to figure out why sphinx is adding in a `label` within the `chapter` tags. I seem to recall there was a nice way to visualise the `ast` -- is this right?

I guess I am wondering if `visit_title` and `visit_label` method calls are in a different order.

**Comment by chrisjsewell** [comment]
In ExecutableBookProject/MyST-Parser#123 there are now test fixtures that test and clearly define the AST output from myst-parser: https://github.com/ExecutableBookProject/MyST-Parser/tree/markdown-it/tests/test_renderers/fixtures (in particular see syntax_elements.md).

You could compare this with the test fixtures in docutils, e.g. https://github.com/docutils-mirror/docutils/blob/master/test/test_parsers/test_rst/test_section_headers.py

Note you may want to try running this project with `myst-parser==0.8.0a3`, before the new implementation is merged, and have a quick check if any issues are inadvertently caused (hopefully not!)

**Comment by chrisjsewell** [comment]
Also in https://github.com/ExecutableBookProject/MyST-NB/blob/92757ba449130784d2642f7f8fae75f7dd79cfb7/tests/conftest.py#L42, is an example of loading the `.doctree` generated in the sphinx build folder, hwich you can then get the text representation of the AST the `.pformat()`:

```python
from pathlib import Path
import pickle

document = pickle.loads(Path("path/to/build/file.doctree").read_bytes())
print(document.pformat())
```

**Comment by mmcky** [comment]
thanks @chrisjsewell -- this is really helpful.

**Comment by mmcky** [comment]
So I have updated to `myst-parser==0.8.0a3` and the ordering of the `AST` looks to be correct. There are still some edges cases but `make latexpdf` now runs. This repository is configured to use `xelatex` as there is unicode in the source files. 

[mystexampleproject.pdf](https://github.com/ExecutableBookProject/myst-parser.example-project/files/4411895/mystexampleproject.pdf)

**Comment by mmcky** [comment]
Edge problems:

1. Titles are not just the title text: `(scalar_d)= Dynamics in One Dimension`
1. some inline math is not getting rendered and showing as raw latex in the pdf. (`$S = \mathbb R_+ = [0, \infty)$.`

The latex for the above issues is:

1. `\chapter{(scalar\_d)= Dynamics in One Dimension}`
1. `\$S = \textbackslash{}mathbb R\_+ = {[}0, \textbackslash{}infty)\$`

**Comment by mmcky** [comment]
So looking at `sphinx` warnings:

```
/Users/matthewmckay/repos-collab/ebp/myst-parser.example-project/source/ar1_processes-MyST.md:9: WARNING: None:any reference target not found: scalar_d
/Users/matthewmckay/repos-collab/ebp/myst-parser.example-project/source/finite_markov-MyST.md:741: WARNING: None:any reference target not found: ar1_processes
/Users/matthewmckay/repos-collab/ebp/myst-parser.example-project/source/finite_markov-MyST.md:970: WARNING: undefined label: mc_eg1-1 (if the link has no caption the label must precede a section header)
```

Might cause the title issues -- will fix this in the source.

**Comment by chrisjsewell** [comment]
`(scalar_d)= Dynamics in One Dimension`; You can't write this in one line, at least not at present, since it is a block level element, i.e. these should be:

```
(scalar_d)=
# Dynamics in One Dimension
```

don't know where you got the other approach from, that's not what's in the docs lol

Although let me know if you think it would be needed

**Comment by chrisjsewell** [comment]
I'll need more info on the 2nd point. When I run this in the test fixtures I correctly get

```xml
<document source="notset">
    <paragraph>
        <math>
            S = \mathbb R_+ = [0, \infty)
        .
```

does it work using the `math` directive?

**Comment by mmcky** [comment]
hey @chrisjsewell does the `parser` assume inline objects are contained on the same line. 

It looks like the issue with inline math for `pdf` is associated with line splits

```
Consider again the linear model $x_{t+1} = a x_t + b$ with $a
\not=1$.
```

the first equation is rendered fine while the later is not. 

This is the same for `html` output also

<img width="448" alt="image" src="https://user-images.githubusercontent.com/8263752/78090435-d4b52d00-7415-11ea-8f39-768965df1a85.png">

**Comment by mmcky** [comment]
> Although let me know if you think it would be needed

Thanks @chrisjsewell I don't think so. I think an independent link as a placeholder in a document should be on its own line.

**Comment by chrisjsewell** [comment]
> does the parser assume inline objects are contained on the same line

For inline math it does yes. This is a consequence of porting this markdown-it plugin, which does not support multi-lines, as mentioned in goessner/markdown-it-texmath#18.
I don't know the reason for this design decision, but it should be quite possible in the future (probably not right now) to make the plugin accept new lines.

**Comment by jstac** [comment]
I just tested the Jupyter markdown parser and it has no issues with rendering

```markdown
$f
g$
```
so this is a likely source of errors.

**Comment by mmcky** [comment]
Yeah - we have a bunch of them across our projects as `sphinx` supports them and we are migrating from `rst`. I think if the `notebook` supports them - we will need to as well (as @jstac points out). I will raise an issue for tracking this on `myst-parser`. thanks @chrisjsewell

**Comment by mmcky** [comment]
https://github.com/ExecutableBookProject/MyST-Parser/issues/124

**Comment by chrisjsewell** [comment]
Please now try `myst-parser==0.8.0a4`

**Comment by mmcky** [comment]
Love your work @chrisjsewell -- nicely done!

**Comment by mmcky** [comment]
With `myst-parser==0.8.0a4` this example now builds `pdf`
