### ISSUE TITLE
Update source_rst with conf.py and static assets

### ISSUE THREAD

**Issue by mmcky** [ExecutableBookProject/myst-parser.example-project#7]
We can update `source_rst` to include:

1. `conf.py` 
2. `_static`
3. update `Makefile`

then it can be another target for building. We can then compare `source_md` and `source_rst`

**Comment by najuzilu** [comment]
That's what I've been doing locally. Would be happy to update `source_rst` to include those additional files.

**Comment by mmcky** [comment]
that would be great - thanks @najuzilu

**Comment by mmcky** [comment]
I just merged a PR to add these elements.
